---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: cont-1
        image: manukonireddy/myrepo:history
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mustafa
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 8080
      targetPort: 80
